[build]
command = "yarn run build"
publish = "dist"

[dev]
command = "yarn run dev"

[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"

[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/api/:splat"

[[redirects]]
force = true
from = "/"
status = 200
to = "/.netlify/functions/api/:splat"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "*"